#!/usr/bin/env python3
"""fetch-fonts.py — download Inter + JetBrains Mono (latin/latin-ext, woff2)
from Google Fonts into docs/assets/fonts/ and generate docs/assets/fonts/fonts.css.

Self-hosts the fonts so the site has no runtime dependency on a CDN.
Run from the repository root:  python3 scripts/fetch-fonts.py
"""

import os
import re
import urllib.request

BASE = "https://fonts.googleapis.com/css2"
FAMILIES = "family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/121.0 Safari/537.36")

OUT_DIR = "docs/assets/fonts"

# Subsets we keep (Italian needs latin-ext).
SUBSETS = ["latin", "latin-ext"]

FAMILY_SLUG = {
    "Inter": "inter",
    "JetBrains Mono": "jetbrainsmono",
}


def get_css():
    url = f"{BASE}?{FAMILIES}&display=swap"
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def parse_blocks(css):
    """Yield (subset, family, weight, url) tuples from the Google Fonts CSS."""
    blocks = re.split(r"/\*\s*([a-z-]+)\s*\*/", css)
    # blocks: [pre, 'latin', css1, 'latin-ext', css2, ...]
    for i in range(1, len(blocks) - 1, 2):
        subset, body = blocks[i], blocks[i + 1]
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", body)
        weight = re.search(r"font-weight:\s*(\d+)", body)
        src = re.search(r"src:\s*url\(([^)]+)\)", body)
        if family and weight and src:
            yield subset, family.group(1), int(weight.group(1)), src.group(1)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    css = get_css()
    seen = {}
    faces = {}

    for subset, family, weight, url in parse_blocks(css):
        slug = FAMILY_SLUG.get(family, family.lower().replace(" ", ""))
        fname = os.path.join(OUT_DIR, f"{slug}-{subset}-{weight}.woff2")
        if fname not in seen:
            print(f"  download {fname}")
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = resp.read()
            with open(fname, "wb") as f:
                f.write(data)
            seen[fname] = True
        faces.setdefault((family, weight), {})[subset] = (
            f"{slug}-{subset}-{weight}.woff2",
            _unicode_range(css, subset, family, weight),
        )

    with open(os.path.join(OUT_DIR, "fonts.css"), "w") as f:
        f.write("/* Auto-generated by scripts/fetch-fonts.py — do not edit. */\n")
        for (family, weight), subsets in sorted(faces.items()):
            for subset in sorted(subsets):
                fname, urange = subsets[subset]
                f.write(f"@font-face {{\n")
                f.write(f"  font-family: '{family}';\n")
                f.write(f"  font-style: normal;\n")
                f.write(f"  font-weight: {weight};\n")
                f.write(f"  font-display: swap;\n")
                f.write(f"  src: url('./{fname}') format('woff2');\n")
                f.write(f"  unicode-range: {urange};\n")
                f.write(f"}}\n")

    print(f"\nwrote {OUT_DIR}/fonts.css + woff2 files")


def _unicode_range(css, subset, family, weight):
    """Re-read the CSS to find the unicode-range for this family/weight/subset."""
    blocks = re.split(r"/\*\s*([a-z-]+)\s*\*/", css)
    for i in range(1, len(blocks) - 1, 2):
        if blocks[i] != subset:
            continue
        body = blocks[i + 1]
        fam = re.search(r"font-family:\s*'([^']+)'", body)
        w = re.search(r"font-weight:\s*(\d+)", body)
        if fam and fam.group(1) == family and w and int(w.group(1)) == weight:
            m = re.search(r"unicode-range:\s*([^;]+);", body)
            if m:
                return m.group(1).strip()
    return "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"


if __name__ == "__main__":
    main()